[package]
name = "battgui"
version = "0.1.0"
edition = "2024"

[dependencies]
battery = "^0.7"
plotters-iced = "0.11"
iced = { version = "0.13", features = ["canvas", "tokio"] }
plotters="0.3"
chrono = "0.4"