name: Rust

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y libfontconfig1-dev

      - name: Build (release)
        run: cargo build --verbose --release

      - name: Run tests
        run: cargo test

      - name: Prepare artifact
        run: |
          mkdir output
          cp target/release/battgui output/

      - name: Archive binary
        run: |
          tar -czvf output/battgui-x86_64-linux.tar.gz -C output battgui

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: battgui-x86_64-linux
          path: output/battgui-x86_64-linux.tar.gz
